name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-16.04
    container: python:3.6-alpine

    steps:
    - uses: actions/checkout@v2

    - name: Install pybuilder
      run: pip install pybuilder==0.11.17

    - name: Install dependencies
      run: pyb install_dependencies

    - name: Execute build
      run: pyb -X

    - name: Install Codecov requirements
      run: |
        apk update
        apk add bash curl

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/reports/coverage.xml
        directory: ./target/reports
        flags: unittests
        fail_ci_if_error: true
