name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build --target build-image -t rest3client:latest .

    - name: Prepare coverage
      run: |
        ID=$(docker create rest3client)
        docker cp $ID:/code/target/reports/rest3client_coverage.xml rest3client_coverage.xml
        sed -i -e 's,filename="rest3client/,filename="src/main/python/rest3client/,g' rest3client_coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: rest3client_coverage.xml
